/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classsch;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
  

/**
 *
 * @author Dell
 */
public class QRreader extends javax.swing.JFrame implements Runnable,ThreadFactory{
    private WebcamPanel panel=null;
    private Webcam webcam=null;
private static final long serialVersionUID= 6441489157408381878L;
private Executor executor=Executors.newSingleThreadExecutor(this);

    /**
     * Creates new form QRreader
     */
    public QRreader() {
        initComponents();
        initWebcam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        result_field = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Take = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        result_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        result_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(result_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 576, 30));

        label1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label1.setText("Bar Code Id");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("cam");
        jButton1.setBorder(null);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        Take.setText("Click");
        Take.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeActionPerformed(evt);
            }
        });
        jPanel1.add(Take, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void result_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_fieldActionPerformed
 
    }//GEN-LAST:event_result_fieldActionPerformed

    private void TakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeActionPerformed
       String Driver = "com.mysql.jdbc.Driver";
String url = "jdbc:mysql://localhost:3306/class_scheduling";
String uName ="root";
String pwd = "9621792087";
Connection conn=null;
 
try {
Class.forName(Driver).newInstance();
conn = DriverManager.getConnection(url, uName, pwd);
Statement stmt = conn.createStatement();
String sql = "UPDATE student_data SET Attendance=Attendance+1 where mobile="+result_field+";";
stmt.executeUpdate(sql);

 
} catch (ClassNotFoundException e) {
// TODO Auto-generated catch block

}
catch (SQLException e) {
// TODO Auto-generated catch block

}
catch (Exception e) {
// TODO Auto-generated catch block

}
finally{
try {
conn.close();
} catch (SQLException e) {
// TODO Auto-generated catch block
}
}        // TODO add your handling code here:
    }//GEN-LAST:event_TakeActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                } else {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QRreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QRreader().setVisible(true);
        });
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Take;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JTextField result_field;
    // End of variables declaration//GEN-END:variables
 
    private void initWebcam(){
    Dimension size = WebcamResolution.QVGA.getSize();
    webcam = Webcam.getWebcams().get(0);
    webcam.setViewSize(size);

  panel = new WebcamPanel(webcam);
 
  panel.setPreferredSize(size);
 panel.setFPSDisplayed(true);
 jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));
executor.execute(this);
}
     @Override
    public void run() {
        do{
            try {
                Thread.sleep(100);
            }
            catch(InterruptedException e){
               e.printStackTrace();
            }
      Result result=null;
            BufferedImage image=null;
        
        if(webcam.isOpen()){
            
                if((image = webcam.getImage())== null){
                continue;
            }
            }
            LuminanceSource source=new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap=new BinaryBitmap(new HybridBinarizer(source));
        try {
            result=new MultiFormatReader().decode(bitmap);
        }
        catch(NotFoundException e)
        {
            
        }
        if(result !=null){
        result_field.setText(result.getText());
        }
        }
        while(true);
                
        
        }
    
    @Override
    public Thread newThread(Runnable r) {
     Thread t=new Thread(r, "My thread");
     t.setDaemon(true);
     return t;
    }
}
