/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classsch;

import static classsch.login_module.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupbutton = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        department = new javax.swing.JComboBox<>();
        mobile = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        enrollmentno = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        signupbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        signupbutton.setText("Sign Up");
        signupbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(signupbutton);
        signupbutton.setBounds(290, 350, 120, 43);
        getContentPane().add(firstname);
        firstname.setBounds(170, 150, 163, 40);

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname);
        lastname.setBounds(530, 150, 168, 40);

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abc", "xyz", "pqr" }));
        department.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(department);
        department.setBounds(200, 20, 230, 40);
        getContentPane().add(mobile);
        mobile.setBounds(220, 280, 170, 40);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));
        year.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(year);
        year.setBounds(220, 80, 160, 40);
        getContentPane().add(enrollmentno);
        enrollmentno.setBounds(220, 210, 170, 40);

        label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label1.setText("Department");
        getContentPane().add(label1);
        label1.setBounds(20, 20, 120, 40);

        label2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label2.setText("Year");
        getContentPane().add(label2);
        label2.setBounds(20, 80, 100, 40);

        label4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label4.setText("Enrollment No");
        getContentPane().add(label4);
        label4.setBounds(20, 210, 130, 40);

        label5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label5.setText("Mobile");
        getContentPane().add(label5);
        label5.setBounds(20, 280, 140, 40);

        label6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label6.setText("First Name");
        getContentPane().add(label6);
        label6.setBounds(20, 150, 130, 40);

        label3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label3.setText("Last Name");
        getContentPane().add(label3);
        label3.setBounds(360, 150, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsch/FvqFgnM.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-169, -10, 980, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed

  try {
          
          
    Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Class_scheduling","root","9621792087");
   String sql="INSERT INTO login_info2 (department,year,firstname,lastname,enrollmentno,mobile) VALUES (?,?,?,?,?,?)";
    
   PreparedStatement pst=con.prepareStatement(sql);
   
       String po1=department.getSelectedItem().toString();
       String po2=year.getSelectedItem().toString();
            pst.setString(1,po1);
         pst.setString(2,po2);
              pst.setString(3,firstname.getText());
              pst.setString(4,lastname.getText());
              pst.setString(5,enrollmentno.getText());
              pst.setString(6,mobile.getText());
              
      int rs=pst.executeUpdate();
    
    
    
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
    
    }//GEN-LAST:event_signupbuttonActionPerformed

    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField enrollmentno;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField mobile;
    private javax.swing.JButton signupbutton;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
